@startuml
'https://plantuml.com/class-diagram


class JsonFileParser {
private String jsonString
    private File file;
    private Scanner s;
    private JSONObject jsonObj;
    private JSONArray jsonProductsArray;
    private boolean productFoundStatus;

JsonFileParser(String fileName)
private void initScanner (String fileName)
private void readJSONFile()
private void initJSONObject()
private void initJSONProductsArray()
public void searchHandlerOfProductsArray(String productName)
private void printProductNotFound()
private void printProduct(int index)
private int linearSearchProductsArray(String productName)
public boolean getProductFoundStatus()

}

@enduml