@startuml
'https://plantuml.com/class-diagram


class WebsiteGenerator {

private Scanner s;
    private boolean wantsJavaScriptFolderStatus;
    private boolean wantsCSSFolderStatus;
    private String websiteName;
    private String websiteAuthor;
    private String cwdPathWebsiteFolder,
    private String htmlBase;

WebsiteGenerator()
private void initScanner()
public void processWebsiteCreation()
private void askFilesToGenerate()
private void generateWebsiteDirectoryContents()
}


@enduml